# Ch4. Numpy基础

In [4]:
import numpy as np
my_arr = np.arange(1000000)
my_list=list(range(1000000))

In [51]:
%time for _ in range(10): my_arr2=my_arr*2

Wall time: 18 ms


In [39]:
%time for _ in range(10):my_list2=[x*2 for x in my_list]

Wall time: 675 ms


## 4.1 Numpy ndarry:多维数组对象

Numpy的核心特征之一是N-维数组对象 ---ndarray

In [48]:
#生成随机数组
data=np.random.randn(2,3)
data

array([[ 0.96266007, -0.38294135, -0.26972181],
       [-1.56218999, -1.05728503,  1.21219704]])

In [55]:
#给data加上数学操作
print(data*10)
print(data+data)

[[  9.62660072  -3.82941354  -2.69721813]
 [-15.62189988 -10.57285032  12.12197035]]
[[ 1.92532014 -0.76588271 -0.53944363]
 [-3.12437998 -2.11457006  2.42439407]]


In [66]:
#每一个ndarray对象都有一个shape的属性，用来表示数组中每一维的数量
#每一个ndarray对象都有一个dtype的属性，用来表示数组的数据类型
print(data.shape)
print(data.dtype)

(2, 3)
float64


### 4.1.1 生成ndarray

In [71]:
#生成数组最简单的方式使用array函数。array函数接收任意的序列型对象
data1=[6,2,3,883.2,0]
arr1=np.array(data1)

#同等长度的列表，会自动转换成多维数组
data2=[[1,2,3],[3,3,4]]
arr2=np.array(data2)

In [73]:
#可以通过检查ndarray的ndim属性来确认数组的维度
arr2.ndim

2

In [82]:
#zeros可以一次性创建全0数组
print(np.zeros(5))

#ones可以一次性创建全1数组
print(np.ones(4))

#如果需要创建高维的数组，需要传递一个shape的元组
print(np.ones((2,3,2)))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1.]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


empty用来创建没有初始化数值的数组。如果用np.empty来生成全0的数组，并不安全，因为它可能会返回未初始化的垃圾数值

In [84]:
# arange 是python的range的数组版
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

### 4.1.2 ndarray的数据类型

In [91]:
#astype可以显示得转换数据类型
arr = np.array([1,2,3])
print(arr)
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

[1 2 3]
int32
float64


使用astype时总是生成一个新的数组，即使传入的dtype与之前的一样